### ISSUE TITLE
运行ML.Net Objection报System.TypeInitializationException错误

### ISSUE THREAD

**Issue by Cassie1Dragon** [dotnet/docs.zh-cn#617]
在运行ML.Net Objection的例子时，出现以下System.TypeInitializationException错误是什么原因？
---
#### 文档详细信息
System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'onnxruntime' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase()
   at Microsoft.ML.OnnxRuntime.NativeMethods..cctor() in C:\agent\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeMethods.cs:line 145
   --- End of inner exception stack trace ---
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor() in C:\agent\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.cs:line 49
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath) in C:\agent\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 34
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary)
   at Microsoft.ML.OnnxCatalog.ApplyOnnxModel(TransformsCatalog catalog, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)
   at onnx_objection_yolo.OnnxModelScorer.LoadModel(String modelLocation) in C:\02_Sun Yangxing\Data\DeepNet_Note\WindowsML_exercise\onnx_objection_yolo\onnx_objection_yolo\OnnxModelScorer.cs:line 48
   at onnx_objection_yolo.OnnxModelScorer.Score(IDataView data) in C:\02_Sun Yangxing\Data\DeepNet_Note\WindowsML_exercise\onnx_objection_yolo\onnx_objection_yolo\OnnxModelScorer.cs:line 75
   at onnx_objection_yolo.Program.Main(String[] args) in C:\02_Sun Yangxing\Data\DeepNet_Note\WindowsML_exercise\onnx_objection_yolo\onnx_objection_yolo\Program.cs:line 108
⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c2f95783-f8d3-b884-a67e-131eba39f59c
* Version Independent ID: 622956b7-6556-7d5b-a6d1-436ceb9e68e6
* Content: [教程：使用 ONNX 深度学习模型检测对象 - ML.NET](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/tutorials/object-detection-onnx)
* Content Source: [docs/machine-learning/tutorials/object-detection-onnx.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/machine-learning/tutorials/object-detection-onnx.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by srvbpigh** [comment]
你好，@Cassie1Dragon，

我们正在改进我们的内部流程和工程管道。遗憾的是，这会导致我们延迟处理你的反馈。

非常感谢你为我们的文章贡献内容，我们期待继续获取你的支持和理解。
